### ISSUE TITLE
Traceback (most recent call last):   File "<dist\obf\main.py>", line 3, in <module>   File "<frozen main>", line 1, in <module> ModuleNotFoundError: No module named 'requests' [8388] Failed to execute script main

### ISSUE THREAD

**Issue by nezh-nl** [coats1337/Discordapp-TokenGrabber#8]
Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
[8388] Failed to execute script main

**Comment by nezh-nl** [comment]
Traceback (most recent call last):
  File "<dist\obf\main.py>", line 3, in <module>
  File "<frozen main>", line 1, in <module>
ModuleNotFoundError: No module named 'requests'
[8388] Failed to execute script main

**Comment by coats1337** [comment]
pip install requests
